on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        id: build
        run: |
          output_file="dist/subscriptions.txt"
          echo "! ----------------------------------" > "$output_file"
          echo "! Title: Thai ads blocker" >> "$output_file"
          echo "! Description: A list of adblock in Thailand." >> "$output_file"
          echo "! Last Modified: $(date)" >> "$output_file"
          echo "! Commit: $(git rev-parse HEAD)" >> "$output_file"
          echo "! Homepage: https://github.com/someuser/somerepo" >> "$output_file"
          echo "! Download: https://someuser.github.io/somerepo/subscriptions.txt" >> "$output_file"
          echo "! ----------------------------------" >> "$output_file"
          echo "" >> "$output_file"
          for filter_file in filters/*.txt; do
            filter_name=$(basename "$filter_file" .txt)
            echo "! ----------- ads filter -------------" >> "$output_file"
            echo "! ----------- $file_name -----------" >> "$output_file"
            cat "$filter_file" >> "$output_file"
            echo "" >> "$output_file"
          done
          echo "Compile filters completed."

      - name: Upload
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: subscriptions
          path: dist/subscriptions.txt
          retention-days: 1
          if-no-files-found: error
