on:
  push:
    branches:
      - main
    paths:
      - 'filters/*.txt'

jobs:
  deploy:
    runs-on: ububtu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Deploy
        run: |
          yarn install
          yarn run deploy
