on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        id: setup
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build
        id: build
        run: |
          yarn install
          yarn run build

      - name: Upload artifact
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: subscriptions
          path: template/subscriptions.txt
          retention-days: 1
          if-no-files-found: error

      - name: Deploy to GitHub Pages
        id: deployment
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: template
